#:schema node_modules/wrangler/config-schema.json
name = "worker name here!"
main = "src/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "count", id = "kv namespace id here, get from cf portal" }
]
